services:
    db:
        image: postgres:16
        container_name: database
        networks:
            - joplin_net
        volumes:
            - /local/joplin:/var/lib/postgresql/data
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # your PG DB password
            - POSTGRES_USER=joplin
            - POSTGRES_DB=joplin_db
    app:
        image: florider89/joplin-server:latest
        container_name: joplin
        networks:
            - joplin_net
        depends_on:
            - db
        ports:
            - "22300:22300"
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=http://${DUMMY_DOMAIN} # put here dummy domain name like http://joplin.sync.com
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # your PG DB password
            - POSTGRES_DATABASE=joplin_db
            - POSTGRES_USER=joplin
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db
    nginx: 
        image: nginx:latest
        ports:
            - 9000:9000
        volumes:
            - /etc/nginx:/etc/nginx
        networks:
            - joplin_net
networks:
    joplin_net:
        driver: bridge